name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.build_type }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      # == Install Dependency Geogram =================================================================================

      - name: Install Dependency Geogram
        run: |
          git clone --recurse-submodules https://github.com/BrunoLevy/geogram.git
          cd geogram
          echo "GEOGRAM_DIR=$(pwd)" >> $GITHUB_ENV
          ./configure.sh
          cd build/Darwin-clang-dynamic-Release
          make -j

      # == Install Dependency Eigen3 ==================================================================================

      - name: Install Dependency Eigen3
        run: |
          brew install eigen
          echo "Eigen3_DIR=$(brew --prefix eigen)/share/eigen3/cmake" >> $GITHUB_ENV

      # == Configure and make =========================================================================================

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      # == Test =======================================================================================================

      - name: Test
        working-directory: build
        run: ctest --output-on-failure -C ${{ matrix.build_type }}
